language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
      name: clang-ninja
      sudo: required
      env: TASK=clang
      dist: xenial
      cache: ccache
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - ninja-build
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
      script: ./travis.sh
      before_deploy:
      - git tag latest -f
      deploy:
        provider: releases
        api_key:
          secure: "$GH_TOKEN"
        overwrite: true
        file: "shards.cfg"
        skip_cleanup: true
        edge: true
        on:
          tags: false
          all_branches: true
          repo: crossuo/shards
