name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
    - uses: actions/checkout@v2
    - name: Check shards
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build xorg-dev libglu1-mesa-dev libalut-dev mesa-common-dev libasound-dev
        sudo apt-get install -y ninja-build xorg-dev libglu1-mesa-dev libalut-dev mesa-common-dev libasound-dev --fix-missing
        pwd
        ls -la
        git clone https://github.com/crossuo/crossuo --depth 1
        git fetch
        git checkout release
        git config advice.addIgnoredFile true
        cmake -B build -S crossuo
        cmake --build build --target shardchk
        ./build/tools/xuoi/shardchk --path shards
    - uses: stefanzweifel/git-auto-commit-action@v4.1.4
      with:
        files: ./shards.cfg
        tag_name: latest-1
      env:
        DRAFT_RELEASE: "true"
        PRE_RELEASE: "true"
        ALLOW_EMPTY_CHANGELOG: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
