name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
    - uses: actions/checkout@v2
    - name: Check shards
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build xorg-dev libglu1-mesa-dev libalut-dev mesa-common-dev libasound-dev
        sudo apt-get install -y ninja-build xorg-dev libglu1-mesa-dev libalut-dev mesa-common-dev libasound-dev --fix-missing
        pwd
        ls -la
        git clone https://github.com/crossuo/crossuo --depth 1
        cmake -B build -S crossuo
        cmake --build build --target shardchk
        ./build/tools/xuoi/shardchk --path shards
        git tag -f latest
        git push origin --tags -f
        git checkout latest
        ls -la
        git config advice.addIgnoredFile true
    - uses: stefanzweifel/git-auto-commit-action@v4.1.4
      with:
        commit_message: Update shards.cfg
        branch: latest
        file_pattern: ./shards.cfg
        repository: .
        commit_user_name: Publish Bot
        commit_user_email: fungos@gmail.com
        commit_author: Danny Angelo Carminati Grein <fungos@gmail.com>
